src/TesteClienteAgenda.UI.Site/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures.Buffers;
using Microsoft.EntityFrameworkCore;
using TesteClienteAgenda.Application.Interfaces;
using TesteClienteAgenda.Application.ViewModels;
using TesteClienteAgenda.Domain.Interfaces.Notifications;
using TesteClienteAgenda.Domain.Models;
using TesteClienteAgenda.Domain.Notifications;
using TesteClienteAgenda.Infra.Data.Context;

namespace TesteClienteAgenda.UI.Site.Controllers
{
    public class ClientesController : BaseController
    {
        private readonly IClienteAppService _clienteAppService;
        private readonly IAgendaAppService _agendaAppService;

        public ClientesController(INotificador notificador, IClienteAppService clienteAppService, IAgendaAppService agendaAppService) : base(notificador)
        {
            _clienteAppService = clienteAppService;
            _agendaAppService = agendaAppService;
        }

        public IActionResult Error()
        {
            var Teste = GetErros();
            return View();
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            return View(await _clienteAppService.ObterTodos());
        }

        public async Task<IActionResult> ManageAgenda(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _clienteAppService.ObterPorId(id.Value);
            if (cliente == null)
            {
                return NotFound();
            }

            if(!cliente.StatusCliente)
                InsereErro("Cliente Inativo!!!");

            foreach (var agenda in await _agendaAppService.ObterPorCliente(id.Value))
            {
                cliente.Agendas.Add(agenda);
            }

            

            return View(cliente);
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _clienteAppService.ObterPorId(id.Value);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClienteViewModel cliente)
        {
            cliente.Cnpj = cliente.Cnpj.Replace(".","").Replace("/","").Replace("-","");
            if (!ModelState.IsValid)
                return View(cliente);

            var clienteResult = await _clienteAppService.Adicionar(cliente);

            if(OperacaoValida())
                return RedirectToAction(nameof(Index));

            return View(cliente);

        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _clienteAppService.ObterPorId(id.Value);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ClienteViewModel cliente)
        {
            cliente.Cnpj = cliente.Cnpj.Replace(".", "").Replace("/", "").Replace("-","");
            if (id != cliente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _clienteAppService.Atualizar(cliente);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await ClienteExists(cliente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if(OperacaoValida())
                    return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _clienteAppService.ObterPorId(id.Value);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //var cliente = await _clienteAppService.ObterPorId(id);
            //if (cliente == null) return NotFound();
            
            await _clienteAppService.Remover(id);


            //if (!OperacaoValida())
             //   return View(cliente);

                TempData["Sucesso"] = "Cliente excluído com sucesso!";
            return RedirectToAction(nameof(Index));

            

        }

        private async Task<bool> ClienteExists(int id)
        {
            return await _clienteAppService.ObterPorId(id) != null;
        }

        protected override void Dispose(bool disposing)
        {
            if(disposing)_clienteAppService.Dispose();
            base.Dispose(disposing);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ImportarArquivo(ClienteViewModel cliente, int id)
        {
            if (cliente.Arquivo != null)
            {
                cliente = await _clienteAppService.LerArquivoExcelECarregarAgendas(cliente);
                cliente = await _clienteAppService.ObterPorId(id);

                foreach (var agenda in await _agendaAppService.ObterPorCliente(id))
                {
                    cliente.Agendas.Add(agenda);
                }
                //return PartialView("_ListAgenda",cliente);
                return RedirectToAction(nameof(ManageAgenda), new {id = cliente.Id});
            }


            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(ClienteViewModel model)
        {
            var cnpj =  model.Cnpj?.Replace(".", "").Replace("/", "").Replace("-","");
            var statusCliente = model.StatusCliente;
            var razaoSocial = model.RazaoSocial;

            return PartialView("_ListClientes", await _clienteAppService.Filtrar(cnpj, razaoSocial, statusCliente));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageAgenda(ClienteViewModel model)
        {
            await _agendaAppService.AplicarTaxa(model.Id, model.Taxa/100);

            var cliente = await _clienteAppService.ObterPorId(model.Id);

            foreach (var agenda in await _agendaAppService.ObterPorCliente(model.Id))
            {
                cliente.Agendas.Add(agenda);
            }

            return RedirectToAction(nameof(ManageAgenda), new {Id = model.Id});
            //return PartialView("_ListAgenda", cliente);



        }

    }
}

src/TesteClienteAgenda.UI.Site/ViewsComponent/SummaryViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TesteClienteAgenda.Domain.Interfaces.Notifications;

namespace TesteClienteAgenda.UI.Site.ViewsComponent
{
    public class SummaryViewComponent:ViewComponent
    {
        private readonly INotificador _notificador;

        public SummaryViewComponent(INotificador notificador)
        {
            _notificador = notificador;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notificador.ObterNotificacoes());

            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Mensagem));

            return View();
        }
    }
}

src/TesteClienteAgenda.UI.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Teste Cliente Agência</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Teste Cliente Agência</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contato</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    @await Component.InvokeAsync("Summary")
</div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Teste Cliente Agenda - <a asp-area="" asp-controller="Home" asp-action="Contact">Contato</a>
        </div>
    </footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="lib/jquery.mask/jquery.mask.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>                                                 
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){	
        $("#cnpj").mask("99.999.999/9999-99");
    });
</script>
@RenderSection("Scripts", required: false)
</body>
</html>